<?xml version="1.0" encoding="utf-8"?><Database Name="dbms" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-CTT3QOT\SQLEXPRESS;Initial Catalog=dbms;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="EnrollmentSystem.Properties.Settings" SettingsPropertyName="dbmsConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admins" Member="admins">
    <Type Name="admin">
      <Column Name="admin_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="admin_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="admin_mi" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="admin_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="admin_address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="admin_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="admin_phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="admin_instructor" Member="instructors" ThisKey="admin_id" OtherKey="admin_id" Type="instructor" />
      <Association Name="admin_student" Member="students" ThisKey="admin_id" OtherKey="admin_id" Type="student" />
      <Association Name="user_account_admin" Member="user_account" ThisKey="u_id" OtherKey="u_id" Type="user_account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.batch" Member="batches">
    <Type Name="batch">
      <Column Name="batch_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="batch_year" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="batch_schoolyear" Member="schoolyears" ThisKey="batch_id" OtherKey="batch_id" Type="schoolyear" />
    </Type>
  </Table>
  <Table Name="dbo.class" Member="classes">
    <Type Name="class">
      <Column Name="class_code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="class_section" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="class_fromTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="class_toTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="class_day" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="crs_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ins_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="room_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="class_enrollment" Member="enrollments" ThisKey="class_code" OtherKey="class_code" Type="enrollment" />
      <Association Name="course_class" Member="course" ThisKey="crs_id" OtherKey="crs_code" Type="course" IsForeignKey="true" />
      <Association Name="instructor_class" Member="instructor" ThisKey="ins_id" OtherKey="ins_id" Type="instructor" IsForeignKey="true" />
      <Association Name="room_class" Member="room" ThisKey="room_id" OtherKey="room_id" Type="room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.course" Member="courses">
    <Type Name="course">
      <Column Name="crs_code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="crs_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="crs_desc" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="year_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prog_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sem_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="course_class" Member="classes" ThisKey="crs_code" OtherKey="crs_id" Type="class" />
      <Association Name="program_course" Member="program" ThisKey="prog_id" OtherKey="prog_id" Type="program" IsForeignKey="true" />
      <Association Name="semester_course" Member="semester" ThisKey="sem_id" OtherKey="sem_id" Type="semester" IsForeignKey="true" />
      <Association Name="year_course" Member="year" ThisKey="year_id" OtherKey="year_id" Type="year" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.enrollment" Member="enrollments">
    <Type Name="enrollment">
      <Column Name="enroll_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="enroll_status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="class_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sy_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="class_enrollment" Member="class" ThisKey="class_code" OtherKey="class_code" Type="class" IsForeignKey="true" />
      <Association Name="schoolyear_enrollment" Member="schoolyear" ThisKey="sy_id" OtherKey="sy_id" Type="schoolyear" IsForeignKey="true" />
      <Association Name="student_enrollment" Member="student" ThisKey="stud_id" OtherKey="stud_id" Type="student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.instructor" Member="instructors">
    <Type Name="instructor">
      <Column Name="ins_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ins_no" Type="System.String" DbType="VarChar(5) NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_mi" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_dob" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ins_age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ins_gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ins_phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="ins_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="admin_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ins_isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="instructor_class" Member="classes" ThisKey="ins_id" OtherKey="ins_id" Type="class" />
      <Association Name="admin_instructor" Member="admin" ThisKey="admin_id" OtherKey="admin_id" Type="admin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.program" Member="programs">
    <Type Name="program">
      <Column Name="prog_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prog_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="program_course" Member="courses" ThisKey="prog_id" OtherKey="prog_id" Type="course" />
      <Association Name="program_student" Member="students" ThisKey="prog_id" OtherKey="prog_id" Type="student" />
    </Type>
  </Table>
  <Table Name="dbo.room" Member="rooms">
    <Type Name="room">
      <Column Name="room_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="room_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="room_class" Member="classes" ThisKey="room_id" OtherKey="room_id" Type="class" />
    </Type>
  </Table>
  <Table Name="dbo.schoolyear" Member="schoolyears">
    <Type Name="schoolyear">
      <Column Name="sy_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="batch_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sem_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="schoolyear_enrollment" Member="enrollments" ThisKey="sy_id" OtherKey="sy_id" Type="enrollment" />
      <Association Name="batch_schoolyear" Member="batch" ThisKey="batch_id" OtherKey="batch_id" Type="batch" IsForeignKey="true" />
      <Association Name="semester_schoolyear" Member="semester" ThisKey="sem_id" OtherKey="sem_id" Type="semester" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.semester" Member="semesters">
    <Type Name="semester">
      <Column Name="sem_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sem_level" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="semester_course" Member="courses" ThisKey="sem_id" OtherKey="sem_id" Type="course" />
      <Association Name="semester_schoolyear" Member="schoolyears" ThisKey="sem_id" OtherKey="sem_id" Type="schoolyear" />
    </Type>
  </Table>
  <Table Name="dbo.student" Member="students">
    <Type Name="student">
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="stud_no" Type="System.String" DbType="VarChar(5) NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_mi" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="stud_bday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="stud_age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="stud_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="stud_isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="prog_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="admin_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_gpa" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
      <Column Name="year_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_sec" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="student_enrollment" Member="enrollments" ThisKey="stud_id" OtherKey="stud_id" Type="enrollment" />
      <Association Name="admin_student" Member="admin" ThisKey="admin_id" OtherKey="admin_id" Type="admin" IsForeignKey="true" />
      <Association Name="program_student" Member="program" ThisKey="prog_id" OtherKey="prog_id" Type="program" IsForeignKey="true" />
      <Association Name="user_account_student" Member="user_account" ThisKey="u_id" OtherKey="u_id" Type="user_account" IsForeignKey="true" />
      <Association Name="year_student" Member="year" ThisKey="year_id" OtherKey="year_id" Type="year" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.user_account" Member="user_accounts">
    <Type Name="user_account">
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="u_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="u_pass" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="user_account_admin" Member="admins" ThisKey="u_id" OtherKey="u_id" Type="admin" />
      <Association Name="user_account_student" Member="students" ThisKey="u_id" OtherKey="u_id" Type="student" />
    </Type>
  </Table>
  <Table Name="dbo.years" Member="years">
    <Type Name="year">
      <Column Name="year_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="year_level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="year_course" Member="courses" ThisKey="year_id" OtherKey="year_id" Type="course" />
      <Association Name="year_student" Member="students" ThisKey="year_id" OtherKey="year_id" Type="student" />
    </Type>
  </Table>
  <Function Name="dbo.accId" Method="accId">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="accIdResult">
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.addBatch" Method="addBatch">
    <Parameter Name="batch_year" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addCrs" Method="addCrs">
    <Parameter Name="crsname" Type="System.String" DbType="Text" />
    <Parameter Name="crs_desc" Type="System.String" DbType="Text" />
    <Parameter Name="crs_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="crs_prog" Type="System.Int32" DbType="Int" />
    <Parameter Name="sem" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addRoom" Method="addRoom">
    <Parameter Name="room" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addSchoolyear" Method="addSchoolyear">
    <Parameter Name="batch" Type="System.Int32" DbType="Int" />
    <Parameter Name="sem" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.adminID" Method="adminID">
    <Parameter Name="u_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="adminIDResult">
      <Column Name="admin_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.assignClass" Method="assignClass">
    <Parameter Name="section" Type="System.String" DbType="Text" />
    <Parameter Name="from" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="toTime" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="day" Type="System.String" DbType="Text" />
    <Parameter Name="crs_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="prof_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="room_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.checkAssign" Method="checkAssign">
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <ElementType Name="checkAssignResult">
      <Column Name="result" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.checkEnroll" Method="checkEnroll">
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <Parameter Name="sy" Type="System.Int32" DbType="Int" />
    <ElementType Name="checkEnrollResult">
      <Column Name="enroll_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="enroll_status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="class_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sy_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.checkSection" Method="checkSection">
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <Parameter Name="section" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="checkSectionResult">
      <Column Name="stud_sec" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.checkStud" Method="checkStud">
    <Parameter Name="fname" Type="System.String" DbType="Text" />
    <Parameter Name="lname" Type="System.String" DbType="Text" />
    <ElementType Name="checkStudResult">
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_mi" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="stud_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.checkSY" Method="checkSY">
    <Parameter Name="batch" Type="System.Int32" DbType="Int" />
    <Parameter Name="semester" Type="System.Int32" DbType="Int" />
    <ElementType Name="checkSYResult">
      <Column Name="sy_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="batch_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sem_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.compareSec" Method="compareSec">
    <Parameter Name="section" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="program" Type="System.Int32" DbType="Int" />
    <Parameter Name="sem" Type="System.Int32" DbType="Int" />
    <ElementType Name="compareSecResult">
      <Column Name="class_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.createAcc" Method="createAcc">
    <Parameter Name="uname" Type="System.String" DbType="Text" />
    <Parameter Name="upass" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.delClass" Method="delClass">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.delCrs" Method="delCrs">
    <Parameter Name="name" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.enroll" Method="enroll">
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <Parameter Name="class_code" Type="System.Int32" DbType="Int" />
    <Parameter Name="sy" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getAdmin" Method="getAdmin">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getAdminResult">
      <Column Name="admin_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="admin_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="admin_mi" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="admin_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="admin_address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="admin_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="admin_phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getSchoolyear" Method="getSchoolyear">
    <ElementType Name="getSchoolyearResult">
      <Column Name="sy_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="currentSy" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getStud" Method="getStud">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getStudResult">
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_no" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="stud_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_mi" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="stud_bday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="stud_age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="stud_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="stud_isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="prog_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="admin_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_gpa" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
      <Column Name="year_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_sec" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.insDel" Method="insDel">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insFullname" Method="insFullname">
    <ElementType Name="insFullnameResult">
      <Column Name="ins_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.logId" Method="logId">
    <Parameter Name="uname" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="upass" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="logIdResult">
      <Column Name="admin_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.newAdddInstructor" Method="newAdddInstructor">
    <Parameter Name="ins_fname" Type="System.String" DbType="Text" />
    <Parameter Name="ins_mi" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="ins_lname" Type="System.String" DbType="Text" />
    <Parameter Name="ins_dob" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ins_gender" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="ins_phone" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="ins_email" Type="System.String" DbType="Text" />
    <Parameter Name="admin_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.newStudent" Method="newStudent">
    <Parameter Name="stud_fname" Type="System.String" DbType="Text" />
    <Parameter Name="stud_lname" Type="System.String" DbType="Text" />
    <Parameter Name="stud_mi" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="stud_bday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="stud_address" Type="System.String" DbType="Text" />
    <Parameter Name="stud_phone" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="stud_email" Type="System.String" DbType="Text" />
    <Parameter Name="stud_gender" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="stud_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="stud_gpa" Type="System.Decimal" DbType="Decimal(5,1)" />
    <Parameter Name="prog_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="u_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="admin_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.notAssign" Method="notAssign">
    <ElementType Name="notAssignResult">
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.regularEnroll" Method="regularEnroll">
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <Parameter Name="class" Type="System.Int32" DbType="Int" />
    <Parameter Name="sy" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.searchInstructor" Method="searchInstructor">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="searchInstructorResult">
      <Column Name="ins_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ins_no" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ins_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_mi" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_dob" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ins_age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ins_gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ins_phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="ins_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.searchStudent" Method="searchStudent">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="searchStudentResult">
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_no" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="stud_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_mi" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="stud_bday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="stud_address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="stud_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="stud_gpa" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
      <Column Name="prog_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="year_level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.showClass" Method="showClass">
    <ElementType Name="showClassResult">
      <Column Name="class_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="class_section" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="class_fromTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="class_toTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="class_day" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="crs_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="instructor_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="room_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.showCrs" Method="showCrs">
    <ElementType Name="showCrsResult">
      <Column Name="crs_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crs_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="crs_desc" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="year_level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prog_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.showInstructor" Method="showInstructor">
    <Parameter Name="admin_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="showInstructorResult">
      <Column Name="ins_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ins_no" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ins_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_mi" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ins_dob" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ins_gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ins_age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ins_phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="ins_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.showStudent" Method="showStudent">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="showStudentResult">
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_no" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="stud_fname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_lname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_mi" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="stud_bday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="stud_address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="stud_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="year_level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prog_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="stud_gpa" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.studClass" Method="studClass">
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <Parameter Name="sy" Type="System.Int32" DbType="Int" />
    <ElementType Name="studClassResult">
      <Column Name="crs_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="class_fromTime" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="class_toTime" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="class_day" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="instructor_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="room_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="year_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.studCourse" Method="studCourse">
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <Parameter Name="sy" Type="System.Int32" DbType="Int" />
    <ElementType Name="studCourseResult">
      <Column Name="crs_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="crs_desc" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="year_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.studDel" Method="studDel">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.studId" Method="studId">
    <Parameter Name="user" Type="System.String" DbType="Text" />
    <Parameter Name="pass" Type="System.String" DbType="Text" />
    <ElementType Name="studIdResult">
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.studName" Method="studName">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="studNameResult">
      <Column Name="Fullname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.studSection" Method="studSection">
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <ElementType Name="studSectionResult">
      <Column Name="stud_sec" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateCrs" Method="updateCrs">
    <Parameter Name="crs_code" Type="System.Int32" DbType="Int" />
    <Parameter Name="crs_name" Type="System.String" DbType="Text" />
    <Parameter Name="crs_desc" Type="System.String" DbType="Text" />
    <Parameter Name="crs_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="sem" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateInfostud" Method="updateInfostud">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="email" Type="System.String" DbType="Text" />
    <Parameter Name="gpa" Type="System.Decimal" DbType="Decimal(5,1)" />
    <Parameter Name="year_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="prog_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateInstructor" Method="updateInstructor">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="fname" Type="System.String" DbType="Text" />
    <Parameter Name="mi" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="lname" Type="System.String" DbType="Text" />
    <Parameter Name="dob" Type="System.DateTime" DbType="Date" />
    <Parameter Name="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="gender" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="email" Type="System.String" DbType="Text" />
    <Parameter Name="admin_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateSection" Method="updateSection">
    <Parameter Name="section" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateStudent" Method="updateStudent">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="fname" Type="System.String" DbType="Text" />
    <Parameter Name="lname" Type="System.String" DbType="Text" />
    <Parameter Name="mi" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="dob" Type="System.DateTime" DbType="Date" />
    <Parameter Name="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="address" Type="System.String" DbType="Text" />
    <Parameter Name="phone" Type="System.String" DbType="Text" />
    <Parameter Name="email" Type="System.String" DbType="Text" />
    <Parameter Name="gender" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="prog_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="gpa" Type="System.Decimal" DbType="Decimal(5,1)" />
    <Parameter Name="admin_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.verifyAdmin" Method="verifyAdmin">
    <Parameter Name="full" Type="System.String" DbType="Text" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="verifyAdminResult">
      <Column Name="Fullname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.viewEnrollee" Method="viewEnrollee">
    <ElementType Name="viewEnrolleeResult">
      <Column Name="stud_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stud_lname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="stud_fname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="prog_name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="year_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.acceptEnroll" Method="acceptEnroll">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateClass" Method="updateClass">
    <Parameter Name="ClassCode" Parameter="classCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassSection" Parameter="classSection" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ClassFromTime" Parameter="classFromTime" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="ClassToTime" Parameter="classToTime" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="ClassDay" Parameter="classDay" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="CrsID" Parameter="crsID" Type="System.Int32" DbType="Int" />
    <Parameter Name="InsID" Parameter="insID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoomID" Parameter="roomID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.viewClasstoenroll" Method="viewClasstoenroll">
    <Parameter Name="program" Type="System.Int32" DbType="Int" />
    <ElementType Name="viewClasstoenrollResult">
      <Column Name="class_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crs_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="crs_desc" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="class_fromTime" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="class_toTime" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="class_day" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="instructor_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="room_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="year_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.viewCourse" Method="viewCourse">
    <Parameter Name="student" Type="System.Int32" DbType="Int" />
    <ElementType Name="viewCourseResult">
      <Column Name="crs_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="crs_desc" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.assignedStud" Method="assignedStud">
    <ElementType Name="assignedStudResult">
      <Column Name="stud_sec" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.viewSection" Method="viewSection">
    <Parameter Name="section" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="program" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <ElementType Name="viewSectionResult">
      <Column Name="stud_no" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="List_of_Students" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.yearList" Method="yearList">
    <ElementType Name="yearListResult">
      <Column Name="year_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.progList" Method="progList">
    <ElementType Name="progListResult">
      <Column Name="prog_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prog_name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.newStudentAccount" Method="newStudentAccount">
    <Parameter Name="stud_fname" Type="System.String" DbType="Text" />
    <Parameter Name="stud_lname" Type="System.String" DbType="Text" />
    <Parameter Name="stud_mi" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="stud_bday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="stud_address" Type="System.String" DbType="Text" />
    <Parameter Name="stud_phone" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="stud_email" Type="System.String" DbType="Text" />
    <Parameter Name="stud_gender" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="stud_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="stud_gpa" Type="System.Decimal" DbType="Decimal(5,1)" />
    <Parameter Name="prog_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="u_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="admin_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.viewDeacStudent" Method="viewDeacStudent">
    <ElementType Name="viewDeacStudentResult">
      <Column Name="stud_no" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="List_of_Students" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.activate" Method="activate">
    <Parameter Name="student" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>